name: online_shop
description: "Test project"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.5.3
  flutter: ^3.24.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Log
  pretty_dio_logger: ^1.4.0

  # Service
  freezed: ^2.5.7
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.4
  collection: ^1.18.0
  intl: ^0.19.0

  # State Management
  flutter_bloc: ^8.1.6
  provider: ^6.1.2

  # Networking
  dio: ^5.7.0
  retrofit: ^4.4.0

  # Navigation
  auto_route: ^9.2.2

  # Storage
  shared_preferences: ^2.3.2

  # DI & SL
  injectable: ^2.5.0
  get_it: ^8.0.1

  # Native
  flutter_native_splash: ^2.4.2

  # UI
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # service
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  retrofit_generator: '>=8.0.0 <10.0.0'

flutter_native_splash:
  color: "#42a5f5"

flutter:
  uses-material-design: true
  generate: true